name: Deploy Java Maven App to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Get GitHub Actions IP
        id: ip
        run: |
          CURRENT_IP=$(curl -s https://api.ipify.org)
          echo "ACTION_IP=$CURRENT_IP" >> $GITHUB_ENV
          echo "Current IP: $CURRENT_IP"

      - name: Create Temporary Firewall Rule
        run: |
          RULE_NAME="temp-deploy-$(date +%s)"
          echo "RULE_NAME=$RULE_NAME" >> $GITHUB_ENV
          
          gcloud compute firewall-rules create $RULE_NAME \
            --direction=INGRESS \
            --priority=1000 \
            --network=default \
            --action=ALLOW \
            --rules=tcp:22 \
            --source-ranges=${{ env.ACTION_IP }}/32 \
            --target-tags=${{ secrets.VM_TAG }}
          
          # Wait for firewall rule to propagate
          sleep 30

      - name: Deploy to VM Instance
        run: |
          # Create app directory
          gcloud compute ssh ${{ secrets.VM_NAME }} --zone=${{ secrets.ZONE }} \
            --command="mkdir -p ~/java-app"

          # Copy JAR file to the instance
          gcloud compute scp --zone=${{ secrets.ZONE }} target/*.jar ${{ secrets.VM_NAME }}:~/java-app/app.jar

          # Copy service file and start application
          gcloud compute ssh ${{ secrets.VM_NAME }} --zone=${{ secrets.ZONE }} \
            --command="
              sudo tee /etc/systemd/system/java-app.service << EOF
              [Unit]
              Description=Java Application Service
              After=network.target
              
              [Service]
              User=\$USER
              WorkingDirectory=/home/\$USER/java-app
              ExecStart=/usr/bin/java -jar app.jar
              SuccessExitStatus=143
              TimeoutStopSec=10
              Restart=on-failure
              RestartSec=5
              
              [Install]
              WantedBy=multi-user.target
              EOF
              
              sudo systemctl daemon-reload && \
              sudo systemctl enable java-app && \
              sudo systemctl restart java-app"

      - name: Remove Temporary Firewall Rule
        if: always()
        run: |
          gcloud compute firewall-rules delete ${{ env.RULE_NAME }} --quiet
